spring:
  application:
    name: ez-s3
  docker:
    compose:
      file: docker-compose/compose.yaml
  ssl:
    bundle:
      jks:
        s3:
          truststore:
            type: PKCS12
            location: classpath:tls/truststore.p12
            password: changeit
          keystore:
            type: PKCS12
            location: classpath:tls/keystore.p12
            password: changeit

  cloud:
    aws:
      credentials:
        access-key: minioadmin
        secret-key: minioadmin
      s3:
        enabled: true
        endpoint: https://localhost:9000
        region: us-east-1
        path-style-access-enabled: true